apiVersion: v1
kind: Service 
metadata:
  name: hello-green-whale-svc
  labels:
    app: hello-green-whale-app
spec:
  selector:
    app: hello-green-whale-app
  type: NodePort
  ports:
  - nodePort: 31114
    port: 80
    targetPort: 80
