apiVersion: v1
kind: Service	
metadata:
  name: hello-blue-whale-svc
  labels:
    app: hello-blue-whale-app
spec:
  selector:
    app: hello-blue-whale-app
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
